# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
version: 0.2

phases:
  pre_build:
    commands:
      - DEFAULT_PATH=$(pwd)
      - AWS_MODULE_SOURCE=$(aws ssm get-parameter --name "/cicd/config/cicd-framework/repo-url" --query "Parameter.Value" --output text)
      - AWS_MODULE_GIT_REF=$(aws ssm get-parameter --name "/cicd/config/cicd-framework/repo-git-ref" --query "Parameter.Value" --output text)
      - echo $CUSTOMIZATION
      - |
        ssh_key_parameter=$(aws ssm get-parameter --name /cicd/config/cicd-ssh-key --with-decryption 2> /dev/null || echo "None")
        if [[ $ssh_key_parameter != "None" ]]; then
          ssh_key=$(jq --raw-output ".Parameter.Value" <<< $ssh_key_parameter)
          mkdir -p ~/.ssh
          echo "Host *" >> ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          echo "$ssh_key" > ~/.ssh/ssh_key
          echo -e "\n\n" >>  ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/ssh_key
        fi
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - git clone -b $AWS_MODULE_GIT_REF $AWS_MODULE_SOURCE aws-cicd-core-framework
      - chmod +x ./aws-cicd-core-framework/sources/scripts/creds.sh
      - |
        if [ -d "$CUSTOMIZATION" ]; then
          echo "Found customization" $CUSTOMIZATION
          ./aws-cicd-core-framework/sources/scripts/creds.sh --account-id $VENDED_ACCOUNT_ID
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install -r ./$CUSTOMIZATION/api_helpers/python/requirements.txt
          chmod +x ./$CUSTOMIZATION/api_helpers/$SHELL_SCRIPT
        fi
  build:
    commands:
      - |
        if [ -d "$CUSTOMIZATION" ]; then
          ./$CUSTOMIZATION/api_helpers/$SHELL_SCRIPT
        fi
  post_build:
    commands:
      - echo "Post-Build"
